### ISSUE TITLE
Won't view

### ISSUE THREAD

**Issue by Farfnir** [Plymouth-University-BSc-Computing/soft165-practicals-Farfnir#1]
Will only throw a 404 error when ran.
Probably because the path is wrong?
No idea.

**Comment by shirleyatkinson** [comment]
I need a bit more information to help you on this one.  How are you running the page?  I can't see that you have changed anything so it should all run.  Take a look at the developing web applications podcast on the DLE to help you learn about the development environment.

**Comment by Farfnir** [comment]
I've added in the code now, It didn't commit for some reason.
I cannot view the page at all, I'm not sure how, as I don't have ampps in the lab.
